#!/bin/bash

    # Функция для вывода справки
    show_help() {
    echo "Использование: $(basename "$0") [ПАРАМЕТРЫ]"
    echo "Параметры:"
    echo " -u, —users Вывод списка пользователей и их домашних директорий, отсортированных по алфавиту."
    echo " -p, —processes Вывод списка запущенных процессов, отсортированных по их PID."
    echo " -l ПУТЬ, —log ПУТЬ Перенаправление стандартного вывода в файл, указанный по ПУТИ."
    echo " -e ПУТЬ, —errors ПУТЬ Перенаправление ошибок из stderr в файл, указанный по ПУТИ."
    echo " -h, —help Отображение этого сообщения справки и выход."
    }

    # Функция для вывода списка пользователей и их домашних директорий
    show_users() {
    cat /etc/passwd | awk -F: '{print $1 "\t" $6}' | sort
    }

    # Функция для вывода списка запущенных процессов
    show_processes() {
    ps -eo pid,cmd —sort=pid
    }

    # Функция для перенаправления вывода в файл
    redirect_output() {
    local path=$1
    shift
    "$@" > "$path"
    }

    # Функция для перенаправления ошибок в файл
    redirect_errors() {
    local path=$1
    shift
    "$@" 2> "$path"
    }

    # Основной цикл для ожидания ввода команды
    while true; do
    show_help
    read -p "Введите команду: " command

    case $command in
    -u|--users)
    show_users
    ;;
    -p|--processes)
    show_processes
    ;;
    -l|--log)
    read -p "Введите путь для лога: " log_path
    redirect_output "$log_path" "${@:3}"
    ;;
    -e|--errors)
    read -p "Введите путь для ошибок: " errors_path
    redirect_errors "$errors_path" "${@:3}"
    ;;
    -h|--help)
    show_help
    ;;
    *)
    echo "Неверная команда. Введите -h или —help для получения справки."
    ;;
    esac
    done


